### ISSUE TITLE
Integration with Intern?

### ISSUE THREAD

**Issue by xeoneux** [bitjson/typescript-starter#102]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
I am not able to integrate [Intern](https://theintern.io/) with typescript-starter. What's the correct way to do it?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by bitjson** [comment]
Hey @xeoneux, it’s not currently supported, but I’d be happy to accept a PR making it an option! 

If you’re still having trouble with integrating it manually, I recommend talking to the Intern team – this project is just some simple automation to make getting started faster. After you use typescript-starter, you just have a normal TypeScript project, so integration should work the same way as any other project.

**Comment by bitjson** [comment]
This has gone a bit stale, so I'm going to close this issue. If you're still interested, I'll be happy to take a PR!
