### ISSUE TITLE
Include a .editorconfig?

### ISSUE THREAD

**Issue by johnslemmer** [bitjson/typescript-starter#128]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Have you thought about also including a `.editorconfig`?  I'm willing to provide a pull request for this, but didn't know if you weren't including one for a certain reason.

https://editorconfig.org/

**Comment by bitjson** [comment]
Hey @johnslemmer, thanks for opening an issue.

Projects generated by `typescript-starter` currently use [Prettier](https://prettier.io/) to deterministically format code. Would including an `.editorconfig` file have any added benefit? Or do you mean as an alternative to using Prettier for formatting?

Since switching to Prettier, I haven't personally felt a need for any `.editorconfig` or other formatting-related tooling, but I'd be open to providing other options if there's demand.

**Comment by johnslemmer** [comment]
Thanks for getting back to me! Really love this starter BTW. You have done a kick butt job with it!

I agree prettier is fantastic for formatting code.  However, prettier doesn't configure the editor.  This means that the editor will keep its default configuration.  For example:

By default VSCode has a tab size of 4:

<img width="756" alt="screen shot 2018-10-24 at 6 39 00 pm" src="https://user-images.githubusercontent.com/18610918/47470809-33f02600-d7bc-11e8-99e7-b14cf89218df.png">

And really I notice this issue when I open a new file.  Check this out:

![tabsize medium](https://user-images.githubusercontent.com/18610918/47471300-8c282780-d7be-11e8-8f06-8380a324e545.gif)

So typically when you open an already existing file VScode is smart enough to figure out what the tab size is, but with a new file it just goes with its default: 4.  So, when I begin coding a new file it feels really clunky to have everything at 4 spaces, and then when I save/format prettier makes the correct adjustment.  It would just feel nicer if projects also included `.editorconfig` to configure the editor as prettier is just a formatter. (also, I'm sure VScode isn't the only editor behaving this way).

Anyway, obviously this isn't anything major, but a nice little touch (and obviously I could just change my default config).  But I think it is nice when a repo takes control and is explicit about things like format, linting, and.... editor conifguration.  This issue https://github.com/prettier/prettier/issues/42 has bunch of interesting conversation about why having both is nice (and prettier may even support it).  And `.editorconfig` is so ubiquitous even if someone isn't using an editor with prettier support they will probably still write fairly pretty code.

**Comment by bitjson** [comment]
Thank you!

Ah, I see, thanks for clarifying and for the screen capture 👍

If you're interested in contributing it, I'd be very happy to take a pull request adding this as an option!
