### ISSUE TITLE
npm-scripts-info minor issues

### ISSUE THREAD

**Issue by timhwang21** [bitjson/typescript-starter#138]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Super minor issue. The script for `npm-scripts-info` is under `info` in `package.json` which conflicts with Yarn's `yarn info`.

Could we maybe rename the script name to `scripts-info` or something? If it's not a goal to avoid name collision then feel free to close this!

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by bitjson** [comment]
Hi Tim, thanks for opening an issue!

That's always bothered me too, but I never landed on a script name I like better 😅(so I've just stuck with using `yarn run info`).

It would be best to keep it short – ideally a single, simple-to-type word. If you have any ideas, I'd love to switch it!

**Comment by timhwang21** [comment]
Derp, I entirely forgout about `yarn run info`, that of course solves the problem!

Other suggestions though, `man` or `describe` off the top of my head? Regardless, `yarn run info` is fine for me, feel free to close with or without a fix 🙂

**Comment by bitjson** [comment]
Have you tried just `yarn run`? It's now my go-to, even if I'm pretty sure I know what I want 😅(now if only yarn integrated the functionality from `npm-scripts-info` directly into the `run` command...)

Actually `describe` would be great – probably even a better fit than `info`. If you'd be willing, I'd love to take a PR to change it!
