### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by johnslemmer** [bitjson/typescript-starter#159]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

https://github.com/Microsoft/TypeScript/issues/29288

So based on the above statement from the typescript team it seems like ESLint will be their focus as far as linters go. I think that it would be prudent to have this repo start taking a look at what it would take to transition to ESLint or at least offer it as an option.

Just wanted to track this for now. Certainly isn’t an immediate concern. But let me know how/if I can help.

**Comment by lygstate** [comment]
+1 for es lint

**Comment by SQReder** [comment]
bump for eslint

**Comment by yinxin630** [comment]
+1

**Comment by bitjson** [comment]
Hi everyone – thanks for your patience on this. I'm happy to share that the latest version of `typescript-starter` now uses `eslint`! There are also a few other updates:

- added optional support for `cspell` checking
- switched to AVA's new built-in debugging mode (for easier debugging in vscode)
- moved to TypeScript v4, update all other dependencies

Please open an issue if you notice any problems!
