### ISSUE TITLE
Missing npm-scripts-info dev dependency

### ISSUE THREAD

**Issue by justin-calleja** [bitjson/typescript-starter#175]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

After installing with `npx typescript-starter` - I do not have `npm-scripts-info` in dev dependencies.

**Comment by bitjson** [comment]
Fixed in `v2.4.5`. Thanks for the report @justin-calleja!
