### ISSUE TITLE
npm run cov: missing build dependency open-cli

### ISSUE THREAD

**Issue by barrio** [bitjson/typescript-starter#202]
* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
After fresh install via `npx typescript-starter`, 
the command `npm run cov` fails with
`sh: 1: open-cli: not found`.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Fix: npm i open-cli -D

Please add as a build-dep. TNX.

**Comment by bitjson** [comment]
@barrio thanks for the report! Fixed in https://github.com/bitjson/typescript-starter/commit/b49d79daa25fead5ee1d4c3dd2a111ef6b6b8240.
