### ISSUE TITLE
Cannot run my application

### ISSUE THREAD

**Issue by diversemix** [bitjson/typescript-starter#213]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ x ] question about how to use this project

* **Summary**

When I select to use the "node.js application" :+1: 
![image](https://user-images.githubusercontent.com/8524685/68089464-f60eee80-fe60-11e9-89a8-f1e870a3c621.png)

The resultant package.json appears to contain no command / script to allow running that application- i.e. "node build/main/index.js" 

Am I missing something fundamental here?

**Comment by niksauer** [comment]
Same question here 🤔

**Comment by bitjson** [comment]
Hey y'all – PRs welcome! It might be nice to add an `npm start` script which runs `node build/main/index.js` 👍

Merging into https://github.com/bitjson/typescript-starter/issues/77
