### ISSUE TITLE
How can I set up express server typescript-starter

### ISSUE THREAD

**Issue by drtobbyas** [bitjson/typescript-starter#223]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by bitjson** [comment]
Hi there – the latest version of `typescript-starter` includes a lot of improvements. You can get started by running `npx typescript starter`. Then I'd recommend selecting "Node.js application" and following the instructions in the [Express documentation](https://expressjs.com/). 👍
