### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by miguelocarvajal** [bitjson/typescript-starter#228]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Just wondering what the status of the project is?

When starting a new project I try to use the latest versions of all packages and I notice that TypeScript for example is still using version 3.5.3.

Thanks!

**Comment by chrisk8er** [comment]
same question... I really love this project personally.

**Comment by ciesielskico** [comment]
I just cloned the project and ran `npm run build` without modifying anything and it fails with 

![image](https://user-images.githubusercontent.com/17651898/78254702-95124200-74f6-11ea-94aa-4551d1bd9964.png)

**Comment by maustand** [comment]
> I just cloned the project and ran `npm run build` without modifying anything and it fails with
> 
> ![image](https://user-images.githubusercontent.com/17651898/78254702-95124200-74f6-11ea-94aa-4551d1bd9964.png)

update Ava dependency and it will resolve this problem.
they have fixed this issue after 3.x version but typescript-starter has old dependencies, so this is the reason that it does not work..


for more info: [https://github.com/avajs/ava/pull/2308](url)

**Comment by magick93** [comment]
Upgrading ava solved this problem, for me.

But now I get an error when I run `npm run watch`:

```
  ✖ ’sources’ has been removed. Use ’ignoredByWatcher’ to provide glob patterns of files that the watcher should ignore.
```

**Comment by crcastle** [comment]
@magick93 tl;dr you can delete these three lines from your `package.json` to fix that:

```diff
  "ava": {
    "failFast": true,
    "files": [
      "build/main/**/*.spec.js"
-    ],
-    "sources": [
-      "build/main/**/*.js"
    ]
  },
```

In Ava 3, an `ignoredByWatcher` array replaces the `sources` array but it acts in the opposite way. Instead of watching the specified files, all files are watched except those specified in the `ignoredByWatcher` array.

**Comment by bitjson** [comment]
Hey everyone, sorry to keep you waiting on updates! `typescript-starter` has been upgraded to the latest version of all dependencies, and there are a few new improvements 🚀

- migrated from `tslint` (deprecated) to `eslint`
- added optional support for `cspell` checking
- switch to AVA's new built-in debugging mode (for easier debugging in vscode)

Please open an issue if you notice any problems!
