### ISSUE TITLE
Can't generate docs with circular type

### ISSUE THREAD

**Issue by chrispytoes** [bitjson/typescript-starter#236]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
My project is a nodejs library project. I am trying to generate documentation with `npm run doc` but I keep getting an error on this line:
```
type SchemaValue = 'String' | 'Int' | 'Float' | 'Boolean' | DateConstructor | SchemaValue[] | ObjectComposer;
```
Error: `Type alias 'SchemaValue' circularly references itself.`

However TS compiles and runs this just fine, and all my tests pass. So why can't I document it?

**Comment by bitjson** [comment]
Hi @chrispytoes – thanks for opening an issue! 

This was due to the TypeDoc package being outdated. The latest version of `typescript-starter` should solve this issue, but please let me know if you still have trouble with it.
