### ISSUE TITLE
Cannot find namespace 'WebAssembly'

### ISSUE THREAD

**Issue by tranlehaiquan** [bitjson/typescript-starter#243]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I try to initial project "node" and when start with `npm run watch:test`. I got:

```shell
node_modules/@bitauth/libauth/build/module/lib/bin/secp256k1/secp256k1-wasm-types.d.ts:80:24 - error TS2503: Cannot find namespace 'WebAssembly'.

80     readonly instance: WebAssembly.Instance;
```
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Node: v12.16.1
NPM: v6.14.8
Try both in Macos and windows. Did I do something wrong? Thank you.

**Comment by bitjson** [comment]
@tranlehaiquan thanks for opening an issue! This was an oversight – I just fixed the issue and added automated tests to make sure builds never error in the future.

Just waiting for CI to pass, then I'll have #244 merged and released. 👍

**Comment by bitjson** [comment]
Fix released in https://github.com/bitjson/typescript-starter/commit/586cdb3029ab2c52e2f0893adafbbb017059e1c9 🚀

Thanks!
