### ISSUE TITLE
Coverage doesn't work with node <4.5

### ISSUE THREAD

**Issue by Adamfsk** [bitjson/typescript-starter#25]
* **I'm submitting a ...**
[x ] bug report

The ava library being used is affected by the following bug which causes it to fail to run the coverage:
https://github.com/avajs/ava/issues/1354
They're recommending that engines in package.json is changed to node>=4.5, would probably be a good idea to do the same here :)

**Comment by bitjson** [comment]
Hey @Adamfsk, thanks for submitting this issue! I just made the change and added you as the author in: https://github.com/bitjson/typescript-starter/pull/38/commits/e4aed481de17ef4babe13fa22b971a07ead7a43c
