### ISSUE TITLE
Why there is a dependency of @bitauth/libauth?

### ISSUE THREAD

**Issue by jesusantguerrero** [bitjson/typescript-starter#250]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary** 
  Why there is a dependency of @bitauth/libauth in this project I were about to use this to generate a lib but this package made this starter a little bit suspicious.

Please let me know the reason this project use this. since I think it is the best starter out there and I am interested in use it.
Thanks.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by shushpan** [comment]
@jesusantguerrero it's needed just for [example.](https://github.com/bitjson/typescript-starter/blob/master/src/lib/hash.ts#L3) 
When you generate a lib, then you will have 3 files and specs in `lib` folder, which needed to show how you can organize code, write specs, and docs for your future library. 

I just removed this dependency and example code after generating it.

**Comment by jesusantguerrero** [comment]
Thanks for the response. appreciate it.
