### ISSUE TITLE
enhancements ideas?

### ISSUE THREAD

**Issue by chadbr** [bitjson/typescript-starter#53]
@bitjson 

I've started a few projects based on this structure -- but I've gone what I would call 'more full on' with the class structure, using express, etc. etc.

Would you be interested on collaborating on updating the template with latest typescript, tools, etc. and maybe another repo extended with express js?

Or would you prefer me to fork and go?

thanks for the great work - it was a tremendous help.

  Chad

**Comment by bitjson** [comment]
Hey @chadbr, thanks for opening an issue! Sorry for the delayed response, it's been a busy few months. I'd love to accept pull requests with any ideas you have, and I'd also be very happy to collaborate with you on another repo. Glad to hear this project was helpful for you!

**Comment by bitjson** [comment]
Hey @chadbr – with the latest release, `typescript-starter` now has a fairly comprehensive CLI, so it's possible to add any number of new configuration options. If you have any suggestions, please open an issue or send a PR! 🚀

I'm going to close this particular issue, and we can work in a separate issue for each enhancement.
