### ISSUE TITLE
cannot find module "build/main/index.js" 

### ISSUE THREAD

**Issue by fhchina** [bitjson/typescript-starter#55]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by fhchina** [comment]
When running test

**Comment by bitjson** [comment]
Hi @fhchina – thanks for opening an issue! The latest release adds a lot of improvements – it's much simpler, and tests should "just work".

I'm going to close this for now, but please let me know if I should re-open.
