### ISSUE TITLE
name validator rejects scoped npm package name: @cspotcode/foo-bar

### ISSUE THREAD

**Issue by cspotcode** [bitjson/typescript-starter#68]
* **I'm submitting a ...**
[x] bug report

* **Summary**

When I try to create a scoped package (e.g. `@cspotcode/foo-bar`) the prompt complains that the name must be in kebab case.

**Comment by bitjson** [comment]
Thanks for the report! That function is here: https://github.com/bitjson/typescript-starter/blob/master/src/cli/utils.ts#L33

I'll add support for scoped package names 👍

**Comment by bitjson** [comment]
Published in v2.1.1.
