### ISSUE TITLE
CircleCI testing on multiple node versions?

### ISSUE THREAD

**Issue by cspotcode** [bitjson/typescript-starter#69]
* **I'm submitting a ...**
[x] feature request

* **Summary**

Is there an option for testing on multiple node versions in CircleCI?  Do I add a few calls to `nvm` into the `.circleci/config.yml`?  I'm coming from Travis where you list one or two node versions in an array and it runs on both in parallel.

EDIT: also, an AppVeyor option would be great for when CI needs to run on Windows.  (for example, to catch stuff like the outstanding Windows bug I mentioned in #67)
EDIT2: ...and travis, in case you need free Mac testing.

**Comment by bitjson** [comment]
Great idea, thanks for opening an issue!

I'll definitely add another CircleCI job to test on the latest version of node.

And a Windows CI setup is a great idea for this repo, I'll try to get that in first. (Maybe before merging https://github.com/bitjson/typescript-starter/pull/71 so we can confirm it works.)

And I'm very open to adding both of the others and configuration options. I'll see what I can do.

**Comment by bitjson** [comment]
Published in v2.3.0. Thanks!
