### ISSUE TITLE
Add tslint-language-service plugin

### ISSUE THREAD

**Issue by cspotcode** [bitjson/typescript-starter#76]
* **I'm submitting a ...**
[x] feature request

* **Summary**

tslint has a language service plugin so that tslint runs within the language service and shows linter failures in your editor as red squiggly underlines, the same as type errors.

https://www.npmjs.com/package/tslint-language-service

I'll make a PR at some point; just logging here for the time being.

**Comment by bitjson** [comment]
Is there a reason this needs to be configured in every project? My editor (VS Code) has full TSLint language service support in any TypeScript project since I have the TSLint plugin installed. 

I would think we’d would want to avoid non project-specific configuration of any kind for the starter.

**Comment by cspotcode** [comment]
It looks like they're migrate VSCode's TSLint plugin towards using the
language service plugin.  They explain their motivation here:
https://marketplace.visualstudio.com/items?itemName=eg2.ts-tslint#user-content-differences-between-vscode-tslint-(vnext)-and-vscode-tslint

But maybe it's good to wait till the vnext version leaves preview status.

The idea is that any editor (Vim, Emacs, etc) with the language service can
automatically get TSLint support without installing a TSLint-specific
editor plugin.  It's no more project-specific than all the "scripts" that
the starter copies into package.json, or the tsconfig.json options.

On Sun, Mar 18, 2018 at 10:04 AM, Jason Dreyzehner <notifications@github.com

**Comment by bitjson** [comment]
Oh, I've not been following development for `tslint-language-service`. TIL, thanks!

> But maybe it's good to wait till the vnext version leaves preview status.

Ya, I think it might be best for this starter to stick with the current stable setup. 

I'd definitely be open to a PR adding it as an `extra` option, though.

**Comment by bitjson** [comment]
I think it's safe to say this is "done" now – `tslint` is deprecated and this project has switched to `eslint`, and language services are now ubiquitous, so no additional changes need to be made in this project. 👍
