### ISSUE TITLE
Lodash fp causes issues with watch process

### ISSUE THREAD

**Issue by mshick** [bitjson/typescript-starter#78]
* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Using the map or reduce functions from `lodash/fp` leads to a strange behavior in the watch process, where the results of the tests will flash up briefly, and then the screen is immediately cleared. Normally is stays up until a new watch is triggered, which is necessary for review and debugging.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I've been building a `library` initialized via this project. Things were going well until I attempted to use `lodash/fp`. Using the map or reduce functions from that library leads to the screen clearing immediately as soon as tests finish when in watch mode (`npm run watch`). Can be recreated fairly easily by me by installing lodash + typings, then invoking a function like this from a test:

```js
import { map } from 'lodash/fp';

export const mapFn = (): Array<number> => {
  const mapper = map((): number => {
    return 1;
  });

  return mapper(['a', 'b']);  
};
```

test like:

```js
import { mapFn } from './utils';

test('foo', t => {
  const mapped = mapFn();
  console.log(mapped);
  t.pass();
});
```

The normal (non-fp) map and reduce do not cause this behavior.

**Comment by bitjson** [comment]
Hey @mshick, thanks for the report! I'm not sure if I completely understand the issue. Could you commit your simplified example to a new repo and share it here?

**Comment by mshick** [comment]
@bitjson here you go. I also included a video in the root showing the behavior. You'll see that the behavior happens only when using the auto-curried lodash fp functions. I have a little workaround example in there as well, but it's beyond me as to why `lodash/fp` does this. I suspect it's the interplay of `run-p` and `tsc` and `ava`...

https://github.com/mshick/lodash-fp-bug

**Comment by mshick** [comment]
@bitjson Have you had a chance to review / confirm the behavior I saw? Quite puzzling!

**Comment by bitjson** [comment]
If you're still having trouble with this, I think the latest `typescript-starter` might solve it! (Includes a lot of dependency upgrades, and AVA has become much more stable/reliable over the years.) I'm going to close this for now, but please feel free to open a new issue!
