### ISSUE TITLE
use with deployable web app

### ISSUE THREAD

**Issue by tomdavidson** [bitjson/typescript-starter#8]
* **I'm submitting a ...**
[ x ] question about how to use this project

* **Summary**

Starter looks great for distributing a module. Can you make suggestions on using the starter for a deployable web app rather than for a module?

For example, my web app project has:
```
src/
- server (an express app)
- client (client-side browser app)
- common (modules common to the server and client apps)
```

**Comment by bitjson** [comment]
Yep, this project is really set up to be a more general boilerplate for creating javascript libraries with Typescript. You might be interested in one of these:

- https://github.com/jsynowiec/node-typescript-boilerplate
- https://github.com/AngularClass/angular2-webpack-starter
- https://github.com/angular/universal-starter

**Comment by bitjson** [comment]
(Closing, but let me know if I should reopen.)
