### ISSUE TITLE
package.json name prop not set during interactive config

### ISSUE THREAD

**Issue by mshick** [bitjson/typescript-starter#81]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
The package.json `name` property is not set to the name entered during interactive config.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Can be recreated by starting a new project. The `name` prop typescript-starter spits out is always "typescript-starter". I would expect it to be the name I use during config, or possibly a slugified version of that name.

Not sure if this intentional, but it seems odd.

**Comment by bitjson** [comment]
Thanks for the report @mshick! 

You're definitely right, not sure how I missed that when reviewing the fixtures. 😅 

I'll update that now.

**Comment by bitjson** [comment]
Released in [v2.3.5](https://github.com/bitjson/typescript-starter/blob/master/CHANGELOG.md#235-2018-03-29). Thanks!
