### ISSUE TITLE
Missing changelog command

### ISSUE THREAD

**Issue by jbw91** [bitjson/typescript-starter#85]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

There is no `changelog` command as is shown in the `npm run info` script and on the README.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I simply generated the project as instructed, and there is no changelog command to generate the changelog.

**Comment by bitjson** [comment]
@jbw91 thanks for opening an issue! Looks like I just forgot to update that section of the readme – that script is now `npm run version` to more intuitively align with the naming of [standard-version](https://github.com/conventional-changelog/standard-version), which powers it.

Fixed and released moments ago as v2.3.6 👍
