### ISSUE TITLE
Can't see test results in Windows 10

### ISSUE THREAD

**Issue by matheusgrieger** [bitjson/typescript-starter#89]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

When running `npm run watch`, whenever my application compiles it briefly shows which of my tests errored, but then it detects some more file changes, recompiles and the errors are gone. I cannot see what went wrong in my tests, all that shows up are the type check errors, if any.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

It is a Node app, not intended to run in the browser. Even *with* errors, this is all that the PowerShell shows after displaying errors for less than a second:

```
[20:29:48] File change detected. Starting incremental compilation...


[20:29:49] Compilation complete. Watching for file changes.
```

**Comment by bitjson** [comment]
Hi @matheusgrieger, sorry to leave this waiting!

I think this may be solved in the latest version of `typescript-starter`, so I'm going to go ahead and close this. If it's still a problem, would you mind opening a new issue? Thanks again for the report!
