### ISSUE TITLE
use `--rootDir` in config files

### ISSUE THREAD

**Issue by mhegazy** [bitjson/typescript-starter#9]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
This is rather a suggestion to prevent future bugs, whenever `--outDir` is used, I would recommend setting `--rootDir`, see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does---outdir-moves-output-after-adding-a-new-file for more details.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by bitjson** [comment]
Thanks for sharing! I didn't know that. So right now our `tsconfig.json` includes:

```json
{
  "compilerOptions": {
    "outDir": "build/main",
```

Should that be the following?

```json
{
  "compilerOptions": {
    "outDir": "build/main",
    "rootDir": "./",
```

All the other config files inherit from that one, so I think it's just in that file.

(Mind sending a pull request? Would love to have you as a contributor!)

**Comment by bitjson** [comment]
Thanks @mhegazy!
