### ISSUE TITLE
Require on Node.js

### ISSUE THREAD

**Issue by lucaperret** [bitjson/typescript-starter#90]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
Hi there,
I'm using the generated build within Node.js application.
I've a typescript file (in src/lib) that exports a default class and several interfaces.
When trying to require the CommonJS file, I have to do that:
```js
const lib = require('my-lib').default;
```
How to handle javascript module and CommonJS ?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
https://github.com/Microsoft/TypeScript/issues/2719

**Comment by bitjson** [comment]
Hi there – that code snippet seems to be the right way to import from a CommonJS project. If you're still having trouble, feel free to open a new issue!
