### ISSUE TITLE
UMD Support

### ISSUE THREAD

**Issue by theblushingcrow** [bitjson/typescript-starter#91]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ X] question about how to use this project

* **Summary**
Can we generate UMD code using this project?

**Comment by bitjson** [comment]
Thanks for opening an issue!

Currently no – please see this for the rationale: [How do I bundle my library for the browser?](https://github.com/bitjson/typescript-starter#how-do-i-bundle-my-library-for-the-browser)

If you absolutely need your project to produce a UMD bundle directly, it should be fairly simple to add [Rollup](https://github.com/rollup/rollup), but again, for the reasons in the link above, I think it's less likely that you'll want to do that here.

(Closing this issue for now, but I'm very happy to reopen if you'd like to discuss further.)
