### ISSUE TITLE
Bump to Typescript 2.9

### ISSUE THREAD

**Issue by bitjson** [bitjson/typescript-starter#95]
and enable new options in tsconfig (especially: `resolveJsonModule`)

**Comment by ShinDarth** [comment]
Using `typescript-starter 2.3.8 `,  the generated project has already `"typescript": "^2.9.1"`  in `package.json`.

However I wonder why doesn't it just use the latest TypeScript stable version? (currently `3.0.1`).

**Comment by bitjson** [comment]
https://github.com/bitjson/typescript-starter/commit/9de8b66fadbdb7996d027df9e317967185bcad40
